### ISSUE TITLE
twice Comman Issue Unit.Train in command center 

### ISSUE THREAD

**Issue by lavinoys** [JavaBWAPI/JBWAPI#76]
There is a bug that the command center requests twice when creating a scv.

**Comment by dgant** [comment]
The most likely reason that this would happen is issuing a train command on consecutive frames. I took a [quick peek at your code](https://github.com/lavinoys/jbwapi-kotlin/blob/develop/src/main/kotlin/bot/CommandCenterBot.kt#L9):

```
if (commandCenter.type == UnitType.Terran_Command_Center
            && commandCenter.canTrain()
            && commandCenter.trainingQueue.size <= 0
            && self.minerals() >= 50
        ) {
            commandCenter.train(UnitType.Terran_SCV)
        }
```

This can cause the command center to queue SCVs even when you don't expect it. The reason is because of [latency](https://tl.net/blogs/519872-towards-a-good-sc-bot-p56-latency).

Suppose you're running your bot in single player, which has 2 frames of latency. That means that when you tell your bot to train an SCV, the game does not follow the command until 2 frames later:

- Frame 100: `trainingQueue.size ==0` so you tell Command Center to train an SCV
- Frame 101: `trainingQueue.size ==0` so you tell Command Center to train an SCV
- Frame 102: The Command Center starts training an SCV. `trainingQueue.size == 1`
- Frame 103: The Command Center starts training an SCV. `trainingQueue.size == 2`

Here are two ways to avoid this situation:

1. Enable [latency compensation](https://tl.net/blogs/519872-towards-a-good-sc-bot-p56-latency). This causes (J)BWAPI to present a fictional game state that looks like the game would if there were no latency
2. Don't issue commands to units you've commanded too recently, perhaps by using `unit.getLastCommandFrame()`

But if you've encountered an issue not described here, please let us know how to reproduce it.

**Comment by lavinoys** [comment]
@dgant 
Hello. Thank you for your reply. I read your reply carefully.
1. reply
- how can i settings "latency frames = 6, turn size = 2", Do I have to modify it within the code?
Or do I have to modify it within BWAPI?

2. reply
If you use this command, you cannot request the following command

**Comment by lavinoys** [comment]
My English is not good enough.
Thank you for your understanding.

**Comment by lavinoys** [comment]
I solved it this way. Is this right?
[this code](https://github.com/lavinoys/jbwapi-kotlin/blob/4f403c3fcfb2a785d97fe90cec3f9ba34525d403/src/main/kotlin/listener/CustomListener.kt#L32-L37)

`if (isTwiceReq) {
    isTwiceReq = false
    return
} else {
    isTwiceReq = true
}`

**Comment by Bytekeeper** [comment]
@lavinoys You could join our SSCAIT Discord. You will find a link at the bottom of the "readme" of jbwapi here, in the documentation section. A lot of bot authors are hanging around there and might be able to help. (Ok most likely @dgant will answer there as well :) )

**Comment by lavinoys** [comment]
@dgant @Bytekeeper 
thanks. i solved
[code](https://github.com/lavinoys/jbwapi-kotlin/blob/155f7541344b443138aea36bf76f52b991398c16/src/main/kotlin/listener/CustomListener.kt#L38)
